name: 'Demo action for deployment'

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pull-requests: read

# The jobs key groups together all the jobs that run in the workflow file.
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        # strategy:
        #     matrix:
        #         node-version: [16.x, 18.x]

        # environment:
        #     name: github-pages
        #     url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout Code
              # Action that checks out your repository and downloads it to the runner
              uses: actions/checkout@v4

            - name: Setup Nodejs ${{ matrix.node-version }}
              #action to install the specified version of the Node.js software package on the runner
              uses: actions/setup-node@v3
              with:
                  #   node-version: ${{ matrix.node-version }}
                  node-version: 16
                  cache: npm

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload Static Files
              uses: actions/upload-artifact@v3
              with:
                  name: public-files
                  path: public

            - name: Deploy to GitHub Pages
              #   id: deployment
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: public-files
                  #   branch: gh-pages
