name: CI
on:
    pull_request:
        branches:
            - development
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              # Action that checks out your repository and downloads it to the runner
              uses: actions/checkout@v4

            - name: Setup Nodejs
              #action to install the specified version of the Node.js software package on the runner
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test